use_frameworks!

platform :ios, '13.0'

target 'LLGeneral_Example' do
  pod 'LLGeneral', :path => '../'
  pod 'LLGeneral/UI', :path => '../'
  
  target 'LLGeneral_Tests' do
    inherit! :search_paths

#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
  
end
